# Generated by Django 4.0.5 on 2022-06-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_options_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('id',), 'verbose_name': 'Статия', 'verbose_name_plural': 'Статии'},
        ),
    ]
