# Generated by Django 4.0.5 on 2022-06-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_article_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reading_time',
            field=models.IntegerField(verbose_name='Время чтения '),
        ),
    ]
