# Generated by Django 4.0.5 on 2022-06-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_article_reading_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/images', verbose_name='Фотография')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article', verbose_name='Блог')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ('id',),
            },
        ),
    ]
